version: '3.9'

services:

  # https://hub.docker.com/_/caddy
  caddy:
    image: docker.io/caddy:2.6-alpine
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8443:8443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./tmp/caddy.pem:/etc/caddy/certs/caddy.pem
      - ./tmp/caddy-key.pem:/etc/caddy/certs/caddy-key.pem


  # https://hub.docker.com/r/containous/whoami
  whoami:
    image: docker.io/containous/whoami:v1.5.0
    ports:
      - "127.0.0.1:8081:80"


  # https://hub.docker.com/_/alpine
  alpine:
    image: docker.io/alpine:3.16.2
    command: sh -c "apk update && apk add curl busybox-extras && tail -f /dev/null"
    volumes:
      - ./tmp/rootCA.pem:/rootCA.pem

